### PR TITLE
Disallow failing TX

### LINKED ISSUE #799: app should never ask user to send tx which will fail
image

### LINKED ISSUE #821: NTZ transfer submit is enabled when form is invalid

### PR DESCRIPTION
**Pull request by sunify**
Resolves #821
Resolves #799

I set default threshold for all transactions to `1 000 000` units of gas. As I see it should be enough.

### CODE REVIEW

File: app/containers/TxSubmit/index.js [hunk 1]
```diff
@@ -0,0 +1,133 @@
...
+    isLocked: PropTypes.bool,
+    submitButtonLabel: PropTypes.any,
+    cancelButtonLabel: PropTypes.any,
+    onSubmit: PropTypes.func,
+    onCancel: PropTypes.func,
+    submitting: PropTypes.bool,
+    invalid: PropTypes.bool,
+    canSendTx: PropTypes.bool,
+    gasThreshold: PropTypes.number,
+    possbileFailReason: PropTypes.any,
```
Comment (troggy) [inline app/containers/TxSubmit/index.js]: typo: poss**ib**leFailReason

here and in other places
